from sqlalchemy import Column, Integer, DateTime, MetaData, Sequence, create_engine
import datetime
from sqlalchemy.sql.schema import Table
from sqlalchemy.orm import sessionmaker
#from create_database import *



engine = create_engine('sqlite:///./my_database.db', echo = True)

meta = MetaData()

image_table = Table ('image_table', meta,
    Column('id', Integer, Sequence('user_id_seq'), primary_key=True),
    Column('faces', Integer, autoincrement=False),
    Column('datetime', DateTime, default=datetime.datetime.utcnow) 
    )



meta.create_all(engine)

#SessionLocal = sessionmaker(bind=engine)()
SessionLocal = sessionmaker()


#class Image(Base):
    #__tablename__ = "images"

    #id = Column(Integer, primary_key=True, autoincrement=True) #generated by itself; send value to my_database
    #faces = Column(Integer, autoincrement=False) #get faces with func. create_image from create_writing < main; send value to my_database
    #datetime = Column(DateTime, default=datetime.datetime.utcnow) #generated by itself; send value to my_database
